@hostUrl = https://dev10-idsc3training.stagetrainingids.c3aids.cloud
@tenant = idsc3training
@tag = dev10
@C3AuthToken = 303307bc5e5bb0fa130ea783dd860e916ef1f449800632137329f153bf7ca5947feca690ef72113360a0f50033d10dcf8931bd9ce9f3ebc813f81fb268dd3d76d1be

###
PUT {{hostUrl}}/import/1/{{tenant}}/{{tag}}/SmartBulbMeasurementSource/SmartBulb.csv HTTP/1.1
Content-Type: text/csv
Authorization: {{C3AuthToken}}

< /Users/keitheverett/ID/A C3DI/Working Repos/C3DI_Course_Files/C3DI_Starter_Repo/Data Files/SmartBulb.csv

###
PUT {{hostUrl}}/import/1/{{tenant}}/{{tag}}/PowerGridStatusSetSource/PowerGridStatus1-8.txt HTTP/1.1
Content-Type: text/csv
Authorization: {{C3AuthToken}}

< /Users/keitheverett/ID/A C3DI/Working Repos/C3DI_Course_Files/C3DI_Starter_Repo/Data Files/PowerGridStatus1-8.txt

###
PUT {{hostUrl}}/import/1/{{tenant}}/{{tag}}/SmartBulbToFixtureRelationSource/LightBulbFixture.csv HTTP/1.1
Content-Type: text/csv
Authorization: {{C3AuthToken}}

< /Users/keitheverett/ID/A C3DI/Working Repos/C3DI_Course_Files/C3DI_Starter_Repo/Data Files/LightBulbFixture.csv

###
PUT {{hostUrl}}/import/1/{{tenant}}/{{tag}}/CitySource/City.csv HTTP/1.1
Content-Type: text/csv
Authorization: {{C3AuthToken}}

< /Users/keitheverett/ID/A C3DI/Working Repos/C3DI_Course_Files/C3DI_Starter_Repo/Data Files/City.csv

###